# -*- coding: utf-8 -*-
"""ANALITIKA DATA KEL7_C

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAScS10P3sKx4Y6B0tSAwMULSBYNPCoM
"""

import sys
import streamlit as st
import pandas as pd
import io

# Initialize session state for df if it doesn't exist
if 'df' not in st.session_state:
    st.session_state['df'] = None

uploaded_file = st.file_uploader("Upload file CSV", type=["csv"])

if uploaded_file is not None:
    try:
        # Read the uploaded file directly using pandas
        df = pd.read_csv(uploaded_file)
        st.session_state['df'] = df  # Store df in session state
        st.write("Berhasil membaca file:")
        st.write(df.head())
        buffer = io.StringIO()
        df.info(buf=buffer)
        st.text(buffer.getvalue())

    except Exception as e:
        st.error(f"Terjadi kesalahan saat membaca file: {e}")

"""# Preprocessing Data"""

import streamlit as st
import pandas as pd
import io

# Initialize session state for df_clean if it doesn't exist
if 'df_clean' not in st.session_state:
    st.session_state['df_clean'] = None

st.write("# Preprocessing Data")

if 'df' in st.session_state and st.session_state['df'] is not None:
    df = st.session_state['df'] # Retrieve df from session state

    df_clean = df.copy()
    initial_rows = df_clean.shape[0]

    df_clean = df_clean.drop(columns=['Patient_ID'])

    obj_cols = df_clean.select_dtypes(include=['object']).columns
    for col in obj_cols:
        df_clean[col] = df_clean[col].str.strip()

    smoking_map = {'Never': 0, 'Former': 1, 'Current': 2}
    alcohol_map = {'None': 0, 'Moderate': 1, 'High': 2}
    activity_map = {'Low': 0, 'Moderate': 1, 'High': 2}
    diagnosis_map = {'None': 0, 'Pre-disease': 1, 'Diagnosed': 2}
    binary_map = {'Yes': 1, 'No': 0}
    gender_map = {'Male': 0, 'Female': 1}

    df_clean['Smoking_Status'] = df_clean['Smoking_Status'].map(smoking_map)
    df_clean['Alcohol_Consumption'] = df_clean['Alcohol_Consumption'].map(alcohol_map)
    df_clean['Physical_Activity_Level'] = df_clean['Physical_Activity_Level'].map(activity_map)
    df_clean['Previous_Diagnosis'] = df_clean['Previous_Diagnosis'].map(diagnosis_map)
    df_clean['Family_History'] = df_clean['Family_History'].map(binary_map)
    df_clean['Disease_Risk'] = df_clean['Disease_Risk'].map(binary_map)
    df_clean['Gender'] = df_clean['Gender'].map(gender_map)

    df_clean = df_clean.dropna()

    final_rows = df_clean.shape[0]
    removed_rows = initial_rows - final_rows

    st.write(f"Jumlah baris awal: {initial_rows}")
    st.write(f"Jumlah baris setelah cleaning: {final_rows}")
    st.write(f"Jumlah baris yang dihilangkan: {removed_rows} ({(removed_rows/initial_rows)*100:.2f}%)")

    st.write("5 baris pertama setelah pra-pemrosesan:")
    st.write(df_clean.head())
    buffer = io.StringIO()
    df_clean.info(buf=buffer)
    st.text(buffer.getvalue())

    st.session_state['df_clean'] = df_clean # Store df_clean in session state

else:
    st.warning("Mohon unggah file CSV di bagian atas untuk melanjutkan.")

"""# Exploratory Data Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

st.write("# Exploratory Data Analysis")

if 'df_clean' in st.session_state and st.session_state['df_clean'] is not None:
    df_clean = st.session_state['df_clean']

    plt.figure(figsize=(14, 10))

    plt.subplot(2, 2, 1)
    sns.boxplot(x='Disease_Risk', y='Cholesterol_Level', data=df_clean, palette='Set2')
    plt.title('Sebaran Kolesterol: Sehat (0) vs Berisiko (1)')

    plt.subplot(2, 2, 2)
    sns.boxplot(x='Disease_Risk', y='Genetic_Risk_Score', data=df_clean, palette='Set2')
    plt.title('Skor Risiko Genetik: Sehat (0) vs Berisiko (1)')

    plt.subplot(2, 2, 3)
    sns.countplot(x='Smoking_Status', hue='Disease_Risk', data=df_clean, palette='pastel')
    plt.title('Status Merokok (0=Never, 1=Former, 2=Current)')
    plt.legend(title='Risk', loc='upper right')

    plt.subplot(2, 2, 4)
    sns.scatterplot(x='Blood_Pressure_Systolic', y='Blood_Pressure_Diastolic',
                    hue='Disease_Risk', data=df_clean, alpha=0.6, palette='bright')
    plt.title('Pola Tekanan Darah (Sistolik vs Diastolik)')

    plt.tight_layout()
    st.pyplot(plt) # Use st.pyplot to display the plot

else:
    st.warning("Mohon unggah dan pra-proses file CSV terlebih dahulu.")

"""# Regression Analysis"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import streamlit as st
import pandas as pd

st.write("# Regression Analysis")

if 'df_clean' in st.session_state and st.session_state['df_clean'] is not None:
    df_clean = st.session_state['df_clean']

    X = df_clean.drop(columns=['Disease_Risk'])
    y = df_clean['Disease_Risk']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Scale the features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    log_reg = LogisticRegression(max_iter=1000)
    log_reg.fit(X_train_scaled, y_train)

    y_pred = log_reg.predict(X_test_scaled)

    st.write("--- Evaluasi Model Regresi Logistik ---")
    st.write(f"Akurasi Model: {accuracy_score(y_test, y_pred)*100:.2f}%")
    st.write("\nLaporan Klasifikasi Lengkap:")
    st.text(classification_report(y_test, y_pred))

    st.write("\nConfusion Matrix (Tabel Kebenaran):")

    st.write(pd.DataFrame(confusion_matrix(y_test, y_pred),
                         columns=['Prediksi Sehat', 'Prediksi Sakit'],
                         index=['Aktual Sehat', 'Aktual Sakit']))

    # Note: Coefficients for scaled data are interpreted differently than unscaled data.
    # Here, we show coefficients corresponding to the scaled features.
    coef_df = pd.DataFrame({'Fitur': X.columns, 'Koefisien (Pengaruh)': log_reg.coef_[0]})
    coef_df = coef_df.sort_values(by='Koefisien (Pengaruh)', ascending=False)

    st.write("\n--- Faktor Paling Berpengaruh (Koefisien Regresi) ---")
    st.write(coef_df)

else:
    st.warning("Mohon unggah dan pra-proses file CSV terlebih dahulu.")

"""# Feature Engineering"""

from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

st.write("# Feature Engineering")

if 'df_clean' in st.session_state and st.session_state['df_clean'] is not None:
    df_clean = st.session_state['df_clean']

    df_fe = df_clean.copy()

    df_fe['Pulse_Pressure'] = df_fe['Blood_Pressure_Systolic'] - df_fe['Blood_Pressure_Diastolic']

    df_fe['Lifestyle_Risk'] = ((df_fe['Smoking_Status'] == 2) |
                               (df_fe['Alcohol_Consumption'] == 2) |
                               (df_fe['BMI'] > 30)).astype(int)

    df_fe['Senior_Citizen'] = (df_fe['Age'] > 60).astype(int)


    X_fe = df_fe.drop(columns=['Disease_Risk'])
    y_fe = df_fe['Disease_Risk']

    scaler = StandardScaler()
    X_fe_scaled = scaler.fit_transform(X_fe)

    X_train_fe, X_test_fe, y_train_fe, y_test_fe = train_test_split(X_fe_scaled, y_fe, test_size=0.2, random_state=42)

    log_reg_fe = LogisticRegression(class_weight='balanced', max_iter=1000)
    log_reg_fe.fit(X_train_fe, y_train_fe)

    y_pred_fe = log_reg_fe.predict(X_test_fe)

    st.write("--- Evaluasi Model dengan Feature Engineering ---")
    st.write(f"Akurasi Model: {accuracy_score(y_test_fe, y_pred_fe)*100:.2f}%")

    st.text(classification_report(y_test_fe, y_pred_fe))

    plt.figure(figsize=(8, 6))
    cm = confusion_matrix(y_test_fe, y_pred_fe)

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                xticklabels=['Prediksi Sehat', 'Prediksi Sakit'],
                yticklabels=['Aktual Sehat', 'Aktual Sakit'])

    plt.xlabel('Prediksi Model')
    plt.ylabel('Aktual')
    plt.title('Confusion Matrix Heatmap')
    st.pyplot(plt) # Use st.pyplot to display the plot

else:
    st.warning("Mohon unggah dan pra-proses file CSV terlebih dahulu.")

